-- CREATE DATABASE Livraria;
--
-- CREATE SCHEMA livraria;

CREATE TABLE livro(
    ID INTEGER NOT NULL PRIMARY KEY,
    TITULO VARCHAR,
    AUTOR VARCHAR
);
CREATE TABLE usuario(
    ID INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(80),
    EMAIL VARCHAR(80)

);
CREATE TABLE comentario(
    ID INTEGER NOT NULL PRIMARY KEY,
    AVALIACAO SMALLINT,
    DESCRICAO VARCHAR(255),
    CRIACAO TIMESTAMP,
    ID_USUARIO INTEGER,
    ID_LIVRO INTEGER,

    CONSTRAINT FK_COMENTARIO_USUARIO
        FOREIGN KEY(ID_USUARIO)
        REFERENCES usuario(ID),
    CONSTRAINT FK_COMENTARIO_LIVRO
        FOREIGN KEY(ID_LIVRO)
        REFERENCES livro(ID)
);
